version: build{build}

environment:
  matrix:
  - example: qhexedit
    name: win32
    platform: mingw
    
clone_folder: c:\dev\qhexedit
clone_depth: 5

install:
  - set QTDIR=C:\Qt\5.11.2\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\NSIS";%PATH%
  
before_build:
  - cd c:\dev\qhexedit
  - md build
  - cd build
  
build_script:
  - qmake ..\example\qhexedit.pro
  - mingw32-make
  - windeployqt.exe release\qhexedit.exe
  - makensis ..\deploy.nsi
 
artifacts:
  - path: build\QHexEdit.exe

deploy:
  description: 'Latest QHexEdit Release'
  provider: GitHub
  auth_token:
    secure: WEV9mRJC/pC2HFqJMXbLzEfBXAHu8aGDFIR8ARSip9n6jDJyCz3KstjSPM4VsgKc
  artifact: build\QHexEdit.exe
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
